config/routes.rb
TestItemx::Engine.routes.draw do

  mount Authentify::Engine => "/authentify"  #, :as => "authentify_engine"
  mount Quotex::Engine => "/quotex"  #, :as => "authentify_engine"

  resources :standards
  resources :test_items
  resources :test_plan_logs
  resources :quotes do
    resources :test_itemx_test_plans
  end
  root :to => "test_items#index"
  


  resources :test_plans, :only => [:index]
  resources :quotes do
    collection do
      get 'search'
      put 'search_results'
      get 'stats'
      put 'stats_results'      
    end

    resources :test_plans
  end
 
  resources :test_plans do
    collection do
      get 'search'
      put 'search_results'
    end

    resources :test_samples, :only => [:show, :new, :create, :edit, :update, :destroy]
    resources :test_plan_logs
  end


  match '/view_handler', :to => 'application#view_handler'

end

app/controllers/test_itemx/application_controller.rb
module TestItemx
  class ApplicationController < ActionController::Base
    helper Authentify::SessionsHelper
    helper Authentify::UserPrivilegeHelper
    helper Authentify::AuthentifyUtility
    helper TestItemx::SessionsHelper
    include Authentify::SessionsHelper
    include Authentify::UserPrivilegeHelper
    include Authentify::AuthentifyUtility
    include TestItemx::SessionsHelper
  end
end

app/controllers/test_itemx/standards_controller.rb
# encoding: utf-8 

module TestItemx
  class StandardsController < ApplicationController
   
    before_filter :require_signin
    before_filter :require_employee
  
    helper_method :has_edit_create_right?
   
    def index
      @title = "测试标准"
      if has_edit_create_right?
        @standards = Standard.order("name")
      else
        @standards = Standard.active_std.order("name")
      end
    end
  
    def new
  
      if !has_edit_create_right?
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=无权创建新标准!")
      end
      @standard = Standard.new()
      @title = "输入标准"    
    end
  
    def create
      @standard = Standard.new(params[:standard], :as => :role_new)
      @standard.last_updated_by_id = session[:user_id]
      if has_edit_create_right?
        if @standard.save!
          #send out notification email
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=新标准成功保存！")
        else
          flash.now[:error] = "数据有错误。新标准无法保存！"
          render 'new'
        end
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=无权输入新标准!")
      end
    end
  
    def edit
      if !has_edit_create_right?
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=无权更新标准!")     
      end
      @standard = Standard.find(params[:id])
      @title = "更新标准"  
    end
  
    def update
      @standard = Standard.find(params[:id])
      if has_edit_create_right?
        @standard.last_updated_by_id = session[:user_id]
        if @standard.update_attributes(params[:standard], :as => :role_update)
          #send out notification email
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=标准更改成功保存！")
        else
          flash.new[:error] = "数据有错误。标准更改无法保存！"
          render 'edit'
        end
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=无权更改标准!")
      end    
    end
  
    def show
      @standard = Standard.find(params[:id])
      @title = "标准内容"     
    end
  
    protected
    def has_edit_create_right?
      grant_access?('create', 'test_itemx_standards', nil, nil) || grant_access?('update', 'test_itemx_standards', nil, nil)
      #return true if eng_dept_head? || corp_head? || ceo?
    end
  end
end

app/controllers/test_itemx/test_items_controller.rb
# encoding: utf-8

require_dependency "test_itemx/application_controller"

module TestItemx
  
  class TestItemsController < ApplicationController

    before_filter :require_signin
    #before_filter :require_employee
    
    helper_method :has_edit_right?, :has_create_right?
      
    def index
      @title = "测试项目" 
      if has_edit_right?
        @test_items = TestItem.order("name")
      else
        @test_items = TestItem.active_test_item.order("name")
      end
    end
  
    def new
      @title = "输入测试项目"   
      if has_create_right?
        @test_item = TestItem.new()
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
      end  
    end
  
    def create
      if has_create_right?
        @test_item = TestItem.new(params[:test_item], :as => :role_new)
        @test_item.last_updated_by_id = session[:user_id]
        if @test_item.save
          #email notification
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=已保存测试项目！")
        else
          flash.now[:error] = "无法保存测试项目！"
          render 'new'
        end
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
      end  
    end
  
    def edit
      @title = "更新测试项目" 
      if has_edit_right?
        @test_item = TestItem.find(params[:id])
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=无修改权限！")      
      end    
    end
  
    def update
      if has_edit_right?
        @test_item = TestItem.find(params[:id])
        @test_item.last_updated_by_id = session[:user_id]
        if @test_item.update_attributes(params[:test_item], :as => :role_update)
          #email notification
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=已更新测试项目！")
        else
          flash.now[:error] = "数据错误！"
          render 'edit'
        end
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=无修改权限！")      
      end        
    end
  
    def show
      @title = "测试项目内容"   
      @test_item = TestItem.find(params[:id])  
    end
    
    protected
    
    def has_create_right?
      grant_access?('create', 'test_itemx_test_items', nil, nil)
    end
    
    def has_edit_right?
      grant_access?('update', 'test_itemx_test_items', nil, nil)
    end
  
  end

end

app/controllers/test_itemx/test_plan_logs_controller.rb
#encoding: utf-8

module TestItemx


  class TestPlanLogsController < ApplicationController
    
    before_filter :require_signin
    before_filter :require_employee
    
    helper_method :has_create_right?, :has_destroy_right?
    
    def show
      @title= "开案单内容"
      @test_plan = TestPlan.find(params[:test_plan_id])
      @test_plan_log = TestPlanLog.find(params[:id])
    end
  
    def new
      @title= "输入开案单"    
      @test_plan = TestPlan.find(params[:test_plan_id])
      if has_create_right?
        @test_plan_log = @test_plan.test_plan_logs.new()
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
      end
    end
  
    def create
      @test_plan = TestPlan.find(params[:test_plan_id])
      if has_create_right?  
        @test_plan_log = @test_plan.test_plan_logs.new(params[:test_plan_log], :as => :role_new)
        @test_plan_log.last_updated_by_id = session[:user_id]
        if @test_plan_log.save
          redirect_to quote_test_plan_path(@test_plan.quote, @test_plan), :notice => "Log已保存！"
        else
          flash.now[:error] = '无法保存Log！'
          render 'new'
        end
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
      end
    end
  
    def destroy
    end
  
    protected
    
    
    def has_create_right?
      grant_access?('create', 'test_itemx_test_plan_logs', nil, nil)
    end
    
    def has_edit_right?
      grant_access?('update', 'test_itemx_test_plan_logs', nil, nil)
    end
    
    def has_destroy_right?
      grant_access?('destroy', 'test_itemx_test_plan_logs', nil, nil) 
    end
  end

end

app/controllers/test_itemx/test_plans_controller.rb
# encoding: utf-8

module TestItemx

  
  class TestPlansController < ApplicationController
    
    before_filter :require_signin
    before_filter :require_employee
    before_filter :load_quote
    
    helper_method :has_show_right?, :has_edit_right?, :has_create_right?, :has_log_right?, :quote_approved?, :has_new_sample_right?,
                  :has_all_index_view?, :has_approve_right?
  
    def index
      @title = '开案单'
      #if sales_dept_head? || corp_head? || ceo?
      if has_all_index_view?
        @test_plans = @quote.present? ? @quote.test_plan.order("id DESC").paginate(:per_page => 40, :page => params[:page]) : TestPlan.where('created_at > ?', Time.now - 365.day).order("id DESC").paginate(:per_page => 40, :page => params[:page])
      else
        @test_plans = @quote.present? ? @quote.active_test_plan.order("id DESC").paginate(:per_page => 40, :page => params[:page]) : TestPlan.active_test_plan.where('created_at > ?', Time.now - 365.day).order("id DESC").paginate(:per_page => 40, :page => params[:page])
      end        
    end
  
    def new
      if has_create_right? && quote_approved?(@quote)
        @test_plan = @quote.build_test_plan()
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足或报价尚未批准！")
      end
      
    end
  
    def create
      if has_create_right? && quote_approved?(@quote)
        @test_plan = @quote.build_test_plan(params[:test_plan], :as => :role_new)
        @test_plan.last_updated_by_id = session[:user_id]
        if @test_plan.save
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=开案单已保存！")
        else
          flash.now[:error] = "无法保存开案单！"
          render 'new'
        end
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足或报价尚未批准！")
      end    
    end
  
    def edit
      @title = '更改开案单'
      @test_plan = TestPlan.find(params[:id])
      if !has_edit_right?
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足!")
      end
    end
  
    def update
      if has_edit_right?
        @test_plan = TestPlan.find(params[:id])
        @test_plan.last_updated_by_id = session[:user_id]
        if @test_plan.update_attributes(params[:test_plan], :as => :role_update)
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=开案单已修改！")
        else
          flash.now[:error] = '无法保存修改！'
          render 'edit'
        end
      end
    end
  
    def show
      @title = '开案单内容'
      @test_plan = TestPlan.find(params[:id])
      if !has_show_right?
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
      end    
    end
  
    def search
      @test_plan = TestPlan.new
    end
    
    def search_results
      @test_plan = TestPlan.new(params[:test_plan], :as => :role_search)
      
      @test_plans = @test_plan.find_test_plans  
    end
    
    protected


    def has_create_right?
      #rfq = quote.rfq
      #return true if session[:user_id] == rfq.emc_eng_id && eng?
      #return true if session[:user_id] == rfq.safety_eng_id && eng?
      #return true if eng_dept_head? || corp_head? || ceo? 
      return true if grant_access?('create', 'test_itemx_test_plans', nil, nil) || grant_access?('update', 'test_itemx_test_plans', nil, nil)
           
    end
  
    def has_show_right?
      #rfq = quote.rfq
      #return true if session[:user_id] == rfq.sales_id && sales?
      #return true if session[:user_id] == rfq.emc_eng_id && eng?
      #return true if session[:user_id] == rfq.safety_eng_id && eng?
      #return true if acct?
      #return true if reporter?
      #return true if dept_head? || corp_head? || ceo?
      return true if grant_access?('show', 'test_itemx_test_plans', nil, nil)

    end
    
    def has_edit_right? #(quote)
      #rfq = quote.rfq
      #return true if session[:user_id] == rfq.emc_eng_id && eng?
      #return true if session[:user_id] == rfq.safety_eng_id && eng?
      #return true if eng_dept_head? || corp_head? || ceo?  
      return true if grant_access?('update', 'test_itemx_test_plans', nil, nil)
   
    end
    
    #allow input test log
    def has_log_right? #(quote)
      #rfq = quote.rfq
      #return true if session[:user_id] == rfq.sales_id && sales?
      #return true if session[:user_id] == rfq.emc_eng_id && eng?
      #return true if session[:user_id] == rfq.safety_eng_id && eng?
      #return true if eng_dept_head? || corp_head? || ceo?    
      #return true if grant_access?('create', 'test_itemx_test_plans', nil, nil) || grant_access?('update', 'test_itemx_test_plans', nil, nil)
      return true if grant_access?('create', 'test_itemx_test_plan_logs', nil, nil) || grant_access?('update', 'test_itemx_test_plan_logs', nil, nil)

    end
    
    #allow input test sample
    def has_new_sample_right? #(quote)
      #rfq = quote.rfq
      #return true if session[:user_id] == rfq.emc_eng_id && eng?
      #return true if session[:user_id] == rfq.safety_eng_id && eng?
      #return true if eng_dept_head? || corp_head? || ceo?
      return true if grant_access?('create', 'test_itemx_test_samples', nil, nil) || grant_access?('update', 'test_itemx_test_samples', nil, nil)
        
    end

    def has_all_index_view?
      return true if grant_access?('all_index_view', 'test_itemx_test_plans', nil, nil)
    end

    def has_approve_right?
      return true if grant_access?('approve', 'test_itemx_test_plans', nil, nil)
    end

    def quote_approved?(quote)
      quote.approved_by_customer && quote.approved_by_corp_head
    end
      
    def load_quote
      @quote = Quotex::Quote.find(params[:quote_id]) if params[:quote_id].present?
    end
  end

end

app/controllers/test_itemx/test_samples_controller.rb
# encoding: utf-8

module TestItemx

  class TestSamplesController < ApplicationController
    before_filter :require_signin
    before_filter :require_employee
  
    
    helper_method :has_edit_right?, :has_create_right?, :has_delete_right?
    
    def show
      @test_sample = TestSample.find(params[:id])
      @test_plan = @test_sample.test_plan
    end
  
    def new
      @test_plan = TestPlan.find(params[:test_plan_id])
      @test_sample = @test_plan.test_samples.new
      if !has_create_right?
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
      end
    end
  
    def create
      @test_plan = TestPlan.find(params[:test_plan_id])
      if has_create_right?
        @test_sample = @test_plan.test_samples.new(params[:test_sample], :as => :role_new)
        @test_sample.last_updated_by_id = session[:user_id]
        if @test_sample.save
          redirect_to quote_test_plan_path(@test_plan.quote, @test_plan), :notice => '样品记录已保存！'
        else
          flash.now[:error] = '无法保存！'
          render 'new'
        end 
      end 
    end
    
    def edit
      @test_plan = TestPlan.find(params[:test_plan_id])
      @test_sample = TestSample.find(params[:id])
      if !has_edit_right?
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
      end
    end
  
    def update
      @test_plan = TestPlan.find(params[:test_plan_id])
      @test_sample = TestSample.find(params[:id])   
      if has_edit_right?
        @test_sample.last_updated_by_id = session[:user_id]
        if @test_sample.update_attributes(params[:test_sample], :as => :role_update)
          redirect_to quote_test_plan_path(@test_plan.quote, @test_plan), :notice => '记录已修改！'
        else
          flash.now[:error] = '无法保存！'
          render 'edit'
        end
      end  
    end
    
    def destroy
    end
    
    protected
    
    def has_create_right? #(test_plan)
      #rfq = test_plan.quote.rfq
      #return true if session[:user_id] == rfq.emc_eng_id && eng?
      #return true if session[:user_id] == rfq.safety_eng_id && eng?
      #return true if eng_dept_head? || corp_head? || ceo?   
      return true if grant_access?('create', 'test_itemx_test_samples', nil, nil) || grant_access?('update', 'test_itemx_test_samples', nil, nil)
    end
    
    def has_edit_right? #(test_plan)
      #rfq = test_plan.quote.rfq
      #return true if session[:user_id] == rfq.emc_eng_id && eng?
      #return true if session[:user_id] == rfq.safety_eng_id && eng?
      #return true if eng_dept_head? || corp_head? || ceo? 
      return true if grant_access?('create', 'test_itemx_test_samples', nil, nil) || grant_access?('update', 'test_itemx_test_samples', nil, nil)
    end

    def has_delete_right? #(test_plan)
                        #rfq = test_plan.quote.rfq
                        #return true if session[:user_id] == rfq.emc_eng_id && eng?
                        #return true if session[:user_id] == rfq.safety_eng_id && eng?
                        #return true if eng_dept_head? || corp_head? || ceo?
      return true if grant_access?('delete', 'test_itemx_test_samples', nil, nil)
    end


  end

end

app/helpers/test_itemx/application_helper.rb
# encoding: UTF-8


module TestItemx
  module ApplicationHelper


  def to_chn(str_sym)
    h = {:username => '用户名', 
      :password => '密码', 
      :password_confirmation => '确认密码',
      :user_type => '用户类型',
      :user_levels => '用户职位',
      :role => '职位',
      :updated_at => '修改时间',
      'eng' => '测试工程',
      'customer' => '客户',
      'subcontractor' => '外包商',
      'employee' => '公司员工',
      :sales => '业务员',
      :eng => '工程师',
      :search => '搜索',
      :standard => '测试标准',
      :test_item => '测试项目',
      :lease_usage_record => '测试记录单',
      :quote => '报价单',
      :invoice => '账单',
      :invoice_date => '付款日期',
      :paid_out_date => '付清日期',
      :overdue_days => '过期未付天数',
      :test_plan => '开案单',
      :customer => '客户',
      :earliest_created_at => '最早创建日期',
      :latest_created_at => '最晚创建日期',
      :category => '产品/厂家分类',
      :search_results => '搜索结果',
      :stats => '统计',
      :keyword => '关键字'}
    h[str_sym]
  end


  end
end

app/helpers/test_itemx/sessions_helper.rb
# encoding: utf-8
module TestItemx


  module SessionsHelper
    
    def return_sample_unit
      ['个', '台', '套', '件', '根', '米', '升', '立方米']
    end
     
     
  end  # module

end

app/views/test_itemx/test_plans/_form_edit.html.erb
<%= simple_form_for([@quote, @test_plan]) do |f| %>    

  <div class="input"><label class="string">报价# ：</label><%= @quote.id %></div>
  <div class="input"><label class="string">客户 ：</label><%= @quote.rfq.customer.name %></div>
  <div class="input"><label class="string">产品名称 ：</label><%= @quote.rfq.product.name %></div> 
  <div class="input"><label class="string">产品型号 ：</label><%= @quote.rfq.product.model %></div> 
  <div class="input"><label class="string">测试 ：</label><%= @quote.rfq.emc_eng.name if @quote.rfq.emc_eng_id.present? %></div> 
  <div class="input"><label class="string">安规 ：</label><%= @quote.rfq.safety_eng.name if @quote.rfq.safety_eng_id.present? %></div>   
  <div class="input"><label class="string">业务员 ：</label><%= @quote.rfq.sales.name %></div>   

  <%= f.input :sample_requirement, :label => '样品要求：', :input_html => {:rows => 3} %> 
   
  <%= f.input :start_date, :label => '开始日期 ：', :as => :string %> 
  <%= f.input :finish_date, :label => '结束日期 ：', :as => :string %>   
  <%= f.input :sample_qty, :label => '样品数量：' %>
  <%= f.input :unit, :collection => return_sample_unit, :label => '样品单位：' %>    
  <% if has_approve_right? %>
    <%= f.input :approved_by_dept_head, :label => '部门批准？：', :collection => [['',''], ['Yes', true], ['No', false]], :selected => @quote.approved_by_dept_head %>
  <% else %>
    <div><label class="string">部门批准？ ：</label>&nbsp;&nbsp;<%= @test_plan.approved_by_dept_head unless @test_plan.approved_by_dept_head.nil? %> </div>
  <% end %>
   
  <%= f.button :submit, '保存' %>  
<% end %> 

app/views/test_itemx/test_plans/edit.html.erb
<div id="main_body">
<h1>更改开案单</h1>
<%= render 'form_edit' %>

<%= link_to 'Back', SUBURI + "/view_handler?index=0" %>
</div>

app/views/test_itemx/test_plans/index.html.erb
<div id="main_body">
	<h1>开案单</h1>
<div class="emclab_pagination"><%= will_paginate %></div>
</p>
<table>
  <tr>
  	<th>#</th>
    <th>日期</th>
    <th>RFQ#/产品名称/型号</th>    
    <th>客户</th>
    <th>开始日期</th>
    <th>部门批准？</th>   
    <th>样品要求</th> 
    <th>测试</th>           
    <th>安规</th>       
    <th>业务员</th>
    <th></th>
  </tr>
  <% @test_plans.each do |r| %>
    <tr>
      <% if has_show_right? %>
        <td><%= link_to r.id.to_s, SUBURI + "/view_handler?index=1&url=#{quote_test_plan_path(r.quote_id, r)}"  %></td>
      <% else %>
        <td><%= r.id %></td>    
      <% end %>  
      <td><%= r.created_at.strftime('%Y/%m/%d') %></td>
      <td>#<%=r.quote.rfq_id.to_s %><%=r.quote.rfq.product.name %> &nbsp; <%=r.quote.rfq.product.model %></td>
      <td><%= r.quote.rfq.customer.short_name %></td>
      <td><%= r.start_date.strftime('%Y/%m/%d') %></td> 
      <td><%= r.approved_by_dept_head %></td> 
      <td><%= r.sample_requirement %></td>
      <td><%= r.quote.rfq.emc_eng.name if r.quote.rfq.emc_eng_id.present? %></td>  
      <td><%= r.quote.rfq.safety_eng.name if r.quote.rfq.safety_eng_id.present? %></td>                     
      <td><%= r.quote.rfq.sales.name %></td>  
      <td><%= link_to "Edit", SUBURI + "/view_handler?index=1&url=#{edit_quote_test_plan_path(r.quote_id, r)}" if has_edit_right? %></td>
    </tr>
  <% end %>
</table>
<p>
<%= link_to 'Close', SUBURI + "/view_handler?index=0" %> |
<%= link_to to_chn(:search), search_test_plans_path %>
</p>
</div>

app/views/test_itemx/test_plans/new.html.erb
<div id="main_body">
<h1>输入开案单</h1>
<%= render 'form_new' %>

<%= link_to 'Back', SUBURI + "/view_handler?index=0" %>
</div>

app/views/test_itemx/test_plans/search_results.html.erb
<div id="main_body">
<h1><%=to_chn(:search_results)%> - <%= to_chn(:test_plan)%></h1>

</p>
<table>
  <tr>
  	<th></th>
  	<th>#</th>
    <th>日期</th>
    <th>RFQ#/产品名称/型号</th>    
    <th>客户</th>
    <th>开始日期</th>
    <th>部门批准？</th>   
    <th>样品要求</th> 
    <th>测试</th>           
    <th>安规</th>       
    <th>业务员</th>
    <th></th>
  </tr>
  <% @test_plans.each do |r| %>
    <tr>
      <td><%= link_to "Show", SUBURI + "/view_handler?index=1&url=#{quote_test_plan_path(r.quote_id, r)}" if has_show_right?(Quote.find(r.quote_id)) %></td>
      <td><%= r.id %></td>      
      <td><%= r.created_at.strftime('%Y/%m/%d') %></td>
      <td>#<%=r.quote.rfq_id.to_s %><%=r.quote.rfq.product.name %> &nbsp; <%=r.quote.rfq.product.model %></td>
      <td><%= r.quote.rfq.customer.short_name %></td>
      <td><%= r.start_date.strftime('%Y/%m/%d') %></td> 
      <td><%= r.approved_by_dept_head %></td> 
      <td><%= r.sample_requirement %></td>
      <td><%= r.quote.rfq.emc_eng.name if r.quote.rfq.emc_eng_id.present? %></td>  
      <td><%= r.quote.rfq.safety_eng.name if r.quote.rfq.safety_eng_id.present? %></td>                     
      <td><%= r.quote.rfq.sales.name %></td>  
      <td><%= link_to "Edit", SUBURI + "/view_handler?index=1&url=#{edit_quote_test_plan_path(r.quote_id, r)}" if has_edit_right?(Quote.find(r.quote_id)) %></td>
    </tr>
  <% end %>
</table>
<p>
<%= link_to 'Close', SUBURI + "/view_handler?index=0" %> |
<%= link_to to_chn(:search), search_test_plans_path %>
</p>
</div>

app/views/test_itemx/test_plans/show.html.erb
<div id="main_body">
<h1>开案单内容</h1>

<p>
  <b>开案单#:</b>
  <%= @test_plan.id %>
</p>
<p>
  <b>日期:</b>
  <%= @test_plan.created_at.strftime("%Y-%m-%d") %>
</p>
<p>
  <b>客户:</b>
  <%= @quote.rfq.customer.name %>
</p>
<p>
  <b>报价#:</b>
  <%= @quote.id %>
</p>
<p>
  <b>RFQ#:</b>
  <%= @quote.rfq_id %>
</p>
<p>
  <b>产品名称:</b>
  <%= @quote.rfq.product.name %>
</p>

<p>
  <b>开始日期:</b>
  <%= @test_plan.start_date.strftime("%Y-%m-%d") %>
</p>
<p>
  <b>结束日期:</b>
  <%= @test_plan.finish_date.strftime("%Y-%m-%d") if @test_plan.finish_date.present? %>
</p>
<p>
  <b>样品要求:</b>
  <%= @test_plan.sample_requirement %>
</p>
<p>
  <b>样品数量:</b>
  <%= @test_plan.sample_qty %><%= @test_plan.unit %>
</p>
<p>
  <b>测试:</b>
  <%= @quote.rfq.emc_eng.name if @quote.rfq.emc_eng_id.present? %>
</p>
<p>
  <b>安规:</b>
  <%= @quote.rfq.safety_eng.name if @quote.rfq.safety_eng_id.present? %>
</p>
<p>
  <b>业务员:</b>
  <%= @quote.rfq.sales.name %>
</p>

<p>
  <b>输入/更改:</b>
  <%= @test_plan.last_updated_by.name if !@test_plan.last_updated_by_id.nil? && @test_plan.last_updated_by_id > 0 %>
</p>
<p>
  <b>样品记录:</b>	
  <ul>
  <% @test_plan.test_samples.order("created_at DESC").each do |f| %>
  <li>
  <%= link_to 'Edit', edit_test_plan_test_sample_path(@test_plan, f, :format => :js), :remote => true if has_new_sample_right?(@quote) %>&nbsp;&nbsp;<%= link_to f.created_at.strftime("%Y-%m-%d").to_s + ", " + f.name, test_plan_test_sample_path(@test_plan, f, :format => :js), :remote => true %>
  </li>
<% end %>
</ul>
</p>

<p>
  <b>开案单Log:</b>	
  <ul>
  <% @test_plan.test_plan_logs.order("created_at DESC").each do |f| %>
  <li>
  <%= link_to f.created_at.strftime("%Y-%m-%d").to_s + ", " + f.content[0..20], test_plan_test_plan_log_path(@test_plan, f, :format => :js), :remote => true %>
  </li>
<% end %>
</ul>
</p>

  <%= link_to 'Back', SUBURI + "/view_handler?index=0", :id => 'close' %>
  <%= link_to '收到样品', new_test_plan_test_sample_path(@test_plan, :format => :js), :remote => true, :id => 'new_sample_link' if has_new_sample_right? %>
  <%= link_to '输入Log', new_test_plan_test_plan_log_path(@test_plan, :format => :js), :remote => true, :id => 'new_log_link' if has_log_right? %>

</div>